pub struct UCBlock {
    pub start: u32,
    pub end: u32,
    pub description: &'static str,
    pub tex_name: &'static str,
}

pub fn get_uc_blocks() -> [UCBlock; 280] {
    const UC_BLOCKS: [UCBlock; 280] = [
        UCBlock { start: 0x0000, end: 0x007F, description: "Basic Latin", tex_name: "basiclatin" },
        UCBlock { start: 0x0080, end: 0x00FF, description: "Latin-1 Supplement", tex_name: "latinsupplement" },
        UCBlock { start: 0x0100, end: 0x017F, description: "Latin Extended-A", tex_name: "latinextendeda" },
        UCBlock { start: 0x0180, end: 0x024F, description: "Latin Extended-B", tex_name: "latinextendedb" },
        UCBlock { start: 0x0250, end: 0x02AF, description: "IPA Extensions", tex_name: "ipaextensions" },
        UCBlock { start: 0x02B0, end: 0x02FF, description: "Spacing Modifier Letters", tex_name: "spacingmodifierletters" },
        UCBlock { start: 0x0300, end: 0x036F, description: "Combining Diacritical Marks", tex_name: "combiningdiacriticalmarks" },
        UCBlock { start: 0x0370, end: 0x03FF, description: "Greek and Coptic", tex_name: "greekandcoptic" },
        UCBlock { start: 0x0400, end: 0x04FF, description: "Cyrillic", tex_name: "cyrillic" },
        UCBlock { start: 0x0500, end: 0x052F, description: "Cyrillic Supplement", tex_name: "cyrillicsupplement" },
        UCBlock { start: 0x0530, end: 0x058F, description: "Armenian", tex_name: "armenian" },
        UCBlock { start: 0x0590, end: 0x05FF, description: "Hebrew", tex_name: "hebrew" },
        UCBlock { start: 0x0600, end: 0x06FF, description: "Arabic", tex_name: "arabic" },
        UCBlock { start: 0x0700, end: 0x074F, description: "Syriac", tex_name: "syriac" },
        UCBlock { start: 0x0750, end: 0x077F, description: "Arabic Supplement", tex_name: "arabicsupplement" },
        UCBlock { start: 0x0780, end: 0x07BF, description: "Thaana", tex_name: "thaana" },
        UCBlock { start: 0x07C0, end: 0x07FF, description: "NKo", tex_name: "nko" },
        UCBlock { start: 0x0800, end: 0x083F, description: "Samaritan", tex_name: "samaritan" },
        UCBlock { start: 0x0840, end: 0x085F, description: "Mandaic", tex_name: "mandaic" },
        UCBlock { start: 0x0860, end: 0x086F, description: "Syriac Supplement", tex_name: "syriacsupplement" },
        UCBlock { start: 0x08A0, end: 0x08FF, description: "Arabic Extended-A", tex_name: "arabicextendeda" },
        UCBlock { start: 0x0900, end: 0x097F, description: "Devanagari", tex_name: "devanagari" },
        UCBlock { start: 0x0980, end: 0x09FF, description: "Bengali", tex_name: "bengali" },
        UCBlock { start: 0x0A00, end: 0x0A7F, description: "Gurmukhi", tex_name: "gurmukhi" },
        UCBlock { start: 0x0A80, end: 0x0AFF, description: "Gujarati", tex_name: "gujarati" },
        UCBlock { start: 0x0B00, end: 0x0B7F, description: "Oriya", tex_name: "oriya" },
        UCBlock { start: 0x0B80, end: 0x0BFF, description: "Tamil", tex_name: "tamil" },
        UCBlock { start: 0x0C00, end: 0x0C7F, description: "Telugu", tex_name: "telugu" },
        UCBlock { start: 0x0C80, end: 0x0CFF, description: "Kannada", tex_name: "kannada" },
        UCBlock { start: 0x0D00, end: 0x0D7F, description: "Malayalam", tex_name: "malayalam" },
        UCBlock { start: 0x0D80, end: 0x0DFF, description: "Sinhala", tex_name: "sinhala" },
        UCBlock { start: 0x0E00, end: 0x0E7F, description: "Thai", tex_name: "thai" },
        UCBlock { start: 0x0E80, end: 0x0EFF, description: "Lao", tex_name: "lao" },
        UCBlock { start: 0x0F00, end: 0x0FFF, description: "Tibetan", tex_name: "tibetan" },
        UCBlock { start: 0x1000, end: 0x109F, description: "Myanmar", tex_name: "myanmar" },
        UCBlock { start: 0x10A0, end: 0x10FF, description: "Georgian", tex_name: "georgian" },
        UCBlock { start: 0x1100, end: 0x11FF, description: "Hangul Jamo", tex_name: "hanguljamo" },
        UCBlock { start: 0x1200, end: 0x137F, description: "Ethiopic", tex_name: "ethiopic" },
        UCBlock { start: 0x1380, end: 0x139F, description: "Ethiopic Supplement", tex_name: "ethiopicsupplement" },
        UCBlock { start: 0x13A0, end: 0x13FF, description: "Cherokee", tex_name: "cherokee" },
        UCBlock { start: 0x1400, end: 0x167F, description: "Unified Canadian Aboriginal Syllabics", tex_name: "unifiedcanadianaboriginalsyllabics" },
        UCBlock { start: 0x1680, end: 0x169F, description: "Ogham", tex_name: "ogham" },
        UCBlock { start: 0x16A0, end: 0x16FF, description: "Runic", tex_name: "runic" },
        UCBlock { start: 0x1700, end: 0x171F, description: "Tagalog", tex_name: "tagalog" },
        UCBlock { start: 0x1720, end: 0x173F, description: "Hanunoo", tex_name: "hanunoo" },
        UCBlock { start: 0x1740, end: 0x175F, description: "Buhid", tex_name: "buhid" },
        UCBlock { start: 0x1760, end: 0x177F, description: "Tagbanwa", tex_name: "tagbanwa" },
        UCBlock { start: 0x1780, end: 0x17FF, description: "Khmer", tex_name: "khmer" },
        UCBlock { start: 0x1800, end: 0x18AF, description: "Mongolian", tex_name: "mongolian" },
        UCBlock { start: 0x18B0, end: 0x18FF, description: "Unified Canadian Aboriginal Syllabics Extended", tex_name: "unifiedcanadianaboriginalsyllabicsextended" },
        UCBlock { start: 0x1900, end: 0x194F, description: "Limbu", tex_name: "limbu" },
        UCBlock { start: 0x1950, end: 0x197F, description: "Tai Le", tex_name: "taile" },
        UCBlock { start: 0x1980, end: 0x19DF, description: "New Tai Lue", tex_name: "newtailue" },
        UCBlock { start: 0x19E0, end: 0x19FF, description: "Khmer Symbols", tex_name: "khmersymbols" },
        UCBlock { start: 0x1A00, end: 0x1A1F, description: "Buginese", tex_name: "buginese" },
        UCBlock { start: 0x1A20, end: 0x1AAF, description: "Tai Tham", tex_name: "taitham" },
        UCBlock { start: 0x1AB0, end: 0x1AFF, description: "Combining Diacritical Marks Extended", tex_name: "combiningdiacriticalmarksextended" },
        UCBlock { start: 0x1B00, end: 0x1B7F, description: "Balinese", tex_name: "balinese" },
        UCBlock { start: 0x1B80, end: 0x1BBF, description: "Sundanese", tex_name: "sundanese" },
        UCBlock { start: 0x1BC0, end: 0x1BFF, description: "Batak", tex_name: "batak" },
        UCBlock { start: 0x1C00, end: 0x1C4F, description: "Lepcha", tex_name: "lepcha" },
        UCBlock { start: 0x1C50, end: 0x1C7F, description: "Ol Chiki", tex_name: "olchiki" },
        UCBlock { start: 0x1C80, end: 0x1C8F, description: "Cyrillic Extended-C", tex_name: "cyrillicextendedc" },
        UCBlock { start: 0x1CC0, end: 0x1CCF, description: "Sundanese Supplement", tex_name: "sundanesesupplement" },
        UCBlock { start: 0x1CD0, end: 0x1CFF, description: "Vedic Extensions", tex_name: "vedicextensions" },
        UCBlock { start: 0x1D00, end: 0x1D7F, description: "Phonetic Extensions", tex_name: "phoneticextensions" },
        UCBlock { start: 0x1D80, end: 0x1DBF, description: "Phonetic Extensions Supplement", tex_name: "phoneticextensionssupplement" },
        UCBlock { start: 0x1DC0, end: 0x1DFF, description: "Combining Diacritical Marks Supplement", tex_name: "combiningdiacriticalmarkssupplement" },
        UCBlock { start: 0x1E00, end: 0x1EFF, description: "Latin Extended Additional", tex_name: "latinextendedadditional" },
        UCBlock { start: 0x1F00, end: 0x1FFF, description: "Greek Extended", tex_name: "greekextended" },
        UCBlock { start: 0x2000, end: 0x206F, description: "General Punctuation", tex_name: "generalpunctuation" },
        UCBlock { start: 0x2070, end: 0x209F, description: "Superscripts and Subscripts", tex_name: "superscriptsandsubscripts" },
        UCBlock { start: 0x20A0, end: 0x20CF, description: "Currency Symbols", tex_name: "currencysymbols" },
        UCBlock { start: 0x20D0, end: 0x20FF, description: "Combining Diacritical Marks for Symbols", tex_name: "combiningdiacriticalmarksforsymbols" },
        UCBlock { start: 0x2100, end: 0x214F, description: "Letterlike Symbols", tex_name: "letterlikesymbols" },
        UCBlock { start: 0x2150, end: 0x218F, description: "Number Forms", tex_name: "numberforms" },
        UCBlock { start: 0x2190, end: 0x21FF, description: "Arrows", tex_name: "arrows" },
        UCBlock { start: 0x2200, end: 0x22FF, description: "Mathematical Operators", tex_name: "mathematicaloperators" },
        UCBlock { start: 0x2300, end: 0x23FF, description: "Miscellaneous Technical", tex_name: "miscellaneoustechnical" },
        UCBlock { start: 0x2400, end: 0x243F, description: "Control Pictures", tex_name: "controlpictures" },
        UCBlock { start: 0x2440, end: 0x245F, description: "Optical Character Recognition", tex_name: "opticalcharacterrecognition" },
        UCBlock { start: 0x2460, end: 0x24FF, description: "Enclosed Alphanumerics", tex_name: "enclosedalphanumerics" },
        UCBlock { start: 0x2500, end: 0x257F, description: "Box Drawing", tex_name: "boxdrawing" },
        UCBlock { start: 0x2580, end: 0x259F, description: "Block Elements", tex_name: "blockelements" },
        UCBlock { start: 0x25A0, end: 0x25FF, description: "Geometric Shapes", tex_name: "geometricshapes" },
        UCBlock { start: 0x2600, end: 0x26FF, description: "Miscellaneous Symbols", tex_name: "miscellaneoussymbols" },
        UCBlock { start: 0x2700, end: 0x27BF, description: "Dingbats", tex_name: "dingbats" },
        UCBlock { start: 0x27C0, end: 0x27EF, description: "Miscellaneous Mathematical Symbols-A", tex_name: "miscellaneousmathematicalsymbolsa" },
        UCBlock { start: 0x27F0, end: 0x27FF, description: "Supplemental Arrows-A", tex_name: "supplementalarrowsa" },
        UCBlock { start: 0x2800, end: 0x28FF, description: "Braille Patterns", tex_name: "braillepatterns" },
        UCBlock { start: 0x2900, end: 0x297F, description: "Supplemental Arrows-B", tex_name: "supplementalarrowsb" },
        UCBlock { start: 0x2980, end: 0x29FF, description: "Miscellaneous Mathematical Symbols-B", tex_name: "miscellaneousmathematicalsymbolsb" },
        UCBlock { start: 0x2A00, end: 0x2AFF, description: "Supplemental Mathematical Operators", tex_name: "supplementalmathematicaloperators" },
        UCBlock { start: 0x2B00, end: 0x2BFF, description: "Miscellaneous Symbols and Arrows", tex_name: "miscellaneoussymbolsandarrows" },
        UCBlock { start: 0x2C00, end: 0x2C5F, description: "Glagolitic", tex_name: "glagolitic" },
        UCBlock { start: 0x2C60, end: 0x2C7F, description: "Latin Extended-C", tex_name: "latinextendedc" },
        UCBlock { start: 0x2C80, end: 0x2CFF, description: "Coptic", tex_name: "coptic" },
        UCBlock { start: 0x2D00, end: 0x2D2F, description: "Georgian Supplement", tex_name: "georgiansupplement" },
        UCBlock { start: 0x2D30, end: 0x2D7F, description: "Tifinagh", tex_name: "tifinagh" },
        UCBlock { start: 0x2D80, end: 0x2DDF, description: "Ethiopic Extended", tex_name: "ethiopicextended" },
        UCBlock { start: 0x2DE0, end: 0x2DFF, description: "Cyrillic Extended-A", tex_name: "cyrillicextendeda" },
        UCBlock { start: 0x2E00, end: 0x2E7F, description: "Supplemental Punctuation", tex_name: "supplementalpunctuation" },
        UCBlock { start: 0x2E80, end: 0x2EFF, description: "CJK Radicals Supplement", tex_name: "cjkradicalssupplement" },
        UCBlock { start: 0x2F00, end: 0x2FDF, description: "Kangxi Radicals", tex_name: "kangxiradicals" },
        UCBlock { start: 0x2FF0, end: 0x2FFF, description: "Ideographic Description Characters", tex_name: "ideographicdescriptioncharacters" },
        UCBlock { start: 0x3000, end: 0x303F, description: "CJK Symbols and Punctuation", tex_name: "cjksymbolsandpunctuation" },
        UCBlock { start: 0x3040, end: 0x309F, description: "Hiragana", tex_name: "hiragana" },
        UCBlock { start: 0x30A0, end: 0x30FF, description: "Katakana", tex_name: "katakana" },
        UCBlock { start: 0x3100, end: 0x312F, description: "Bopomofo", tex_name: "bopomofo" },
        UCBlock { start: 0x3130, end: 0x318F, description: "Hangul Compatibility Jamo", tex_name: "hangulcompatibilityjamo" },
        UCBlock { start: 0x3190, end: 0x319F, description: "Kanbun", tex_name: "kanbun" },
        UCBlock { start: 0x31A0, end: 0x31BF, description: "Bopomofo Extended", tex_name: "bopomofoextended" },
        UCBlock { start: 0x31C0, end: 0x31EF, description: "CJK Strokes", tex_name: "cjkstrokes" },
        UCBlock { start: 0x31F0, end: 0x31FF, description: "Katakana Phonetic Extensions", tex_name: "katakanaphoneticextensions" },
        UCBlock { start: 0x3200, end: 0x32FF, description: "Enclosed CJK Letters and Months", tex_name: "enclosedcjklettersandmonths" },
        UCBlock { start: 0x3300, end: 0x33FF, description: "CJK Compatibility", tex_name: "cjkcompatibility" },
        UCBlock { start: 0x3400, end: 0x4DBF, description: "CJK Unified Ideographs Extension A", tex_name: "cjkunifiedideographsextensiona" },
        UCBlock { start: 0x4DC0, end: 0x4DFF, description: "Yijing Hexagram Symbols", tex_name: "yijinghexagramsymbols" },
        UCBlock { start: 0x4E00, end: 0x9FFF, description: "CJK Unified Ideographs", tex_name: "cjkunifiedideographs" },
        UCBlock { start: 0xA000, end: 0xA48F, description: "Yi Syllables", tex_name: "yisyllables" },
        UCBlock { start: 0xA490, end: 0xA4CF, description: "Yi Radicals", tex_name: "yiradicals" },
        UCBlock { start: 0xA4D0, end: 0xA4FF, description: "Lisu", tex_name: "lisu" },
        UCBlock { start: 0xA500, end: 0xA63F, description: "Vai", tex_name: "vai" },
        UCBlock { start: 0xA640, end: 0xA69F, description: "Cyrillic Extended-B", tex_name: "cyrillicextendedb" },
        UCBlock { start: 0xA6A0, end: 0xA6FF, description: "Bamum", tex_name: "bamum" },
        UCBlock { start: 0xA700, end: 0xA71F, description: "Modifier Tone Letters", tex_name: "modifiertoneletters" },
        UCBlock { start: 0xA720, end: 0xA7FF, description: "Latin Extended-D", tex_name: "latinextendedd" },
        UCBlock { start: 0xA800, end: 0xA82F, description: "Syloti Nagri", tex_name: "sylotinagri" },
        UCBlock { start: 0xA830, end: 0xA83F, description: "Common Indic Number Forms", tex_name: "commonindicnumberforms" },
        UCBlock { start: 0xA840, end: 0xA87F, description: "Phags-pa", tex_name: "phagspa" },
        UCBlock { start: 0xA880, end: 0xA8DF, description: "Saurashtra", tex_name: "saurashtra" },
        UCBlock { start: 0xA8E0, end: 0xA8FF, description: "Devanagari Extended", tex_name: "devanagariextended" },
        UCBlock { start: 0xA900, end: 0xA92F, description: "Kayah Li", tex_name: "kayahli" },
        UCBlock { start: 0xA930, end: 0xA95F, description: "Rejang", tex_name: "rejang" },
        UCBlock { start: 0xA960, end: 0xA97F, description: "Hangul Jamo Extended-A", tex_name: "hanguljamoextendeda" },
        UCBlock { start: 0xA980, end: 0xA9DF, description: "Javanese", tex_name: "javanese" },
        UCBlock { start: 0xA9E0, end: 0xA9FF, description: "Myanmar Extended-B", tex_name: "myanmarextendedb" },
        UCBlock { start: 0xAA00, end: 0xAA5F, description: "Cham", tex_name: "cham" },
        UCBlock { start: 0xAA60, end: 0xAA7F, description: "Myanmar Extended-A", tex_name: "myanmarextendeda" },
        UCBlock { start: 0xAA80, end: 0xAADF, description: "Tai Viet", tex_name: "taiviet" },
        UCBlock { start: 0xAAE0, end: 0xAAFF, description: "Meetei Mayek Extensions", tex_name: "meeteimayekextensions" },
        UCBlock { start: 0xAB00, end: 0xAB2F, description: "Ethiopic Extended-A", tex_name: "ethiopicextendeda" },
        UCBlock { start: 0xAB30, end: 0xAB6F, description: "Latin Extended-E", tex_name: "latinextendede" },
        UCBlock { start: 0xAB70, end: 0xABBF, description: "Cherokee Supplement", tex_name: "cherokeesupplement" },
        UCBlock { start: 0xABC0, end: 0xABFF, description: "Meetei Mayek", tex_name: "meeteimayek" },
        UCBlock { start: 0xAC00, end: 0xD7AF, description: "Hangul Syllables", tex_name: "hangulsyllables" },
        UCBlock { start: 0xD7B0, end: 0xD7FF, description: "Hangul Jamo Extended-B", tex_name: "hanguljamoextendedb" },
        UCBlock { start: 0xD800, end: 0xDB7F, description: "High Surrogates", tex_name: "highsurrogates" },
        UCBlock { start: 0xDB80, end: 0xDBFF, description: "High Private Use Surrogates", tex_name: "highprivateusesurrogates" },
        UCBlock { start: 0xDC00, end: 0xDFFF, description: "Low Surrogates", tex_name: "lowsurrogates" },
        UCBlock { start: 0xE000, end: 0xF8FF, description: "Private Use Area", tex_name: "privateusearea" },
        UCBlock { start: 0xF900, end: 0xFAFF, description: "CJK Compatibility Ideographs", tex_name: "cjkcompatibilityideographs" },
        UCBlock { start: 0xFB00, end: 0xFB4F, description: "Alphabetic Presentation Forms", tex_name: "alphabeticpresentationforms" },
        UCBlock { start: 0xFB50, end: 0xFDFF, description: "Arabic Presentation Forms-A", tex_name: "arabicpresentationformsa" },
        UCBlock { start: 0xFE00, end: 0xFE0F, description: "Variation Selectors", tex_name: "variationselectors" },
        UCBlock { start: 0xFE10, end: 0xFE1F, description: "Vertical Forms", tex_name: "verticalforms" },
        UCBlock { start: 0xFE20, end: 0xFE2F, description: "Combining Half Marks", tex_name: "combininghalfmarks" },
        UCBlock { start: 0xFE30, end: 0xFE4F, description: "CJK Compatibility Forms", tex_name: "cjkcompatibilityforms" },
        UCBlock { start: 0xFE50, end: 0xFE6F, description: "Small Form Variants", tex_name: "smallformvariants" },
        UCBlock { start: 0xFE70, end: 0xFEFF, description: "Arabic Presentation Forms-B", tex_name: "arabicpresentationformsb" },
        UCBlock { start: 0xFF00, end: 0xFFEF, description: "Halfwidth and Fullwidth Forms", tex_name: "halfwidthandfullwidthforms" },
        UCBlock { start: 0xFFF0, end: 0xFFFF, description: "Specials", tex_name: "specials" },
        UCBlock { start: 0x10000, end: 0x1007F, description: "Linear B Syllabary", tex_name: "linearbsyllabary" },
        UCBlock { start: 0x10080, end: 0x100FF, description: "Linear B Ideograms", tex_name: "linearbideograms" },
        UCBlock { start: 0x10100, end: 0x1013F, description: "Aegean Numbers", tex_name: "aegeannumbers" },
        UCBlock { start: 0x10140, end: 0x1018F, description: "Ancient Greek Numbers", tex_name: "ancientgreeknumbers" },
        UCBlock { start: 0x10190, end: 0x101CF, description: "Ancient Symbols", tex_name: "ancientsymbols" },
        UCBlock { start: 0x101D0, end: 0x101FF, description: "Phaistos Disc", tex_name: "phaistosdisc" },
        UCBlock { start: 0x10280, end: 0x1029F, description: "Lycian", tex_name: "lycian" },
        UCBlock { start: 0x102A0, end: 0x102DF, description: "Carian", tex_name: "carian" },
        UCBlock { start: 0x102E0, end: 0x102FF, description: "Coptic Epact Numbers", tex_name: "copticepactnumbers" },
        UCBlock { start: 0x10300, end: 0x1032F, description: "Old Italic", tex_name: "olditalic" },
        UCBlock { start: 0x10330, end: 0x1034F, description: "Gothic", tex_name: "gothic" },
        UCBlock { start: 0x10350, end: 0x1037F, description: "Old Permic", tex_name: "oldpermic" },
        UCBlock { start: 0x10380, end: 0x1039F, description: "Ugaritic", tex_name: "ugaritic" },
        UCBlock { start: 0x103A0, end: 0x103DF, description: "Old Persian", tex_name: "oldpersian" },
        UCBlock { start: 0x10400, end: 0x1044F, description: "Deseret", tex_name: "deseret" },
        UCBlock { start: 0x10450, end: 0x1047F, description: "Shavian", tex_name: "shavian" },
        UCBlock { start: 0x10480, end: 0x104AF, description: "Osmanya", tex_name: "osmanya" },
        UCBlock { start: 0x104B0, end: 0x104FF, description: "Osage", tex_name: "osage" },
        UCBlock { start: 0x10500, end: 0x1052F, description: "Elbasan", tex_name: "elbasan" },
        UCBlock { start: 0x10530, end: 0x1056F, description: "Caucasian Albanian", tex_name: "caucasianalbanian" },
        UCBlock { start: 0x10600, end: 0x1077F, description: "Linear A", tex_name: "lineara" },
        UCBlock { start: 0x10800, end: 0x1083F, description: "Cypriot Syllabary", tex_name: "cypriotsyllabary" },
        UCBlock { start: 0x10840, end: 0x1085F, description: "Imperial Aramaic", tex_name: "imperialaramaic" },
        UCBlock { start: 0x10860, end: 0x1087F, description: "Palmyrene", tex_name: "palmyrene" },
        UCBlock { start: 0x10880, end: 0x108AF, description: "Nabataean", tex_name: "nabataean" },
        UCBlock { start: 0x108E0, end: 0x108FF, description: "Hatran", tex_name: "hatran" },
        UCBlock { start: 0x10900, end: 0x1091F, description: "Phoenician", tex_name: "phoenician" },
        UCBlock { start: 0x10920, end: 0x1093F, description: "Lydian", tex_name: "lydian" },
        UCBlock { start: 0x10980, end: 0x1099F, description: "Meroitic Hieroglyphs", tex_name: "meroitichieroglyphs" },
        UCBlock { start: 0x109A0, end: 0x109FF, description: "Meroitic Cursive", tex_name: "meroiticcursive" },
        UCBlock { start: 0x10A00, end: 0x10A5F, description: "Kharoshthi", tex_name: "kharoshthi" },
        UCBlock { start: 0x10A60, end: 0x10A7F, description: "Old South Arabian", tex_name: "oldsoutharabian" },
        UCBlock { start: 0x10A80, end: 0x10A9F, description: "Old North Arabian", tex_name: "oldnortharabian" },
        UCBlock { start: 0x10AC0, end: 0x10AFF, description: "Manichaean", tex_name: "manichaean" },
        UCBlock { start: 0x10B00, end: 0x10B3F, description: "Avestan", tex_name: "avestan" },
        UCBlock { start: 0x10B40, end: 0x10B5F, description: "Inscriptional Parthian", tex_name: "inscriptionalparthian" },
        UCBlock { start: 0x10B60, end: 0x10B7F, description: "Inscriptional Pahlavi", tex_name: "inscriptionalpahlavi" },
        UCBlock { start: 0x10B80, end: 0x10BAF, description: "Psalter Pahlavi", tex_name: "psalterpahlavi" },
        UCBlock { start: 0x10C00, end: 0x10C4F, description: "Old Turkic", tex_name: "oldturkic" },
        UCBlock { start: 0x10C80, end: 0x10CFF, description: "Old Hungarian", tex_name: "oldhungarian" },
        UCBlock { start: 0x10E60, end: 0x10E7F, description: "Rumi Numeral Symbols", tex_name: "ruminumeralsymbols" },
        UCBlock { start: 0x11000, end: 0x1107F, description: "Brahmi", tex_name: "brahmi" },
        UCBlock { start: 0x11080, end: 0x110CF, description: "Kaithi", tex_name: "kaithi" },
        UCBlock { start: 0x110D0, end: 0x110FF, description: "Sora Sompeng", tex_name: "sorasompeng" },
        UCBlock { start: 0x11100, end: 0x1114F, description: "Chakma", tex_name: "chakma" },
        UCBlock { start: 0x11150, end: 0x1117F, description: "Mahajani", tex_name: "mahajani" },
        UCBlock { start: 0x11180, end: 0x111DF, description: "Sharada", tex_name: "sharada" },
        UCBlock { start: 0x111E0, end: 0x111FF, description: "Sinhala Archaic Numbers", tex_name: "sinhalaarchaicnumbers" },
        UCBlock { start: 0x11200, end: 0x1124F, description: "Khojki", tex_name: "khojki" },
        UCBlock { start: 0x11280, end: 0x112AF, description: "Multani", tex_name: "multani" },
        UCBlock { start: 0x112B0, end: 0x112FF, description: "Khudawadi", tex_name: "khudawadi" },
        UCBlock { start: 0x11300, end: 0x1137F, description: "Grantha", tex_name: "grantha" },
        UCBlock { start: 0x11400, end: 0x1147F, description: "Newa", tex_name: "newa" },
        UCBlock { start: 0x11480, end: 0x114DF, description: "Tirhuta", tex_name: "tirhuta" },
        UCBlock { start: 0x11580, end: 0x115FF, description: "Siddham", tex_name: "siddham" },
        UCBlock { start: 0x11600, end: 0x1165F, description: "Modi", tex_name: "modi" },
        UCBlock { start: 0x11660, end: 0x1167F, description: "Mongolian Supplement", tex_name: "mongoliansupplement" },
        UCBlock { start: 0x11680, end: 0x116CF, description: "Takri", tex_name: "takri" },
        UCBlock { start: 0x11700, end: 0x1173F, description: "Ahom", tex_name: "ahom" },
        UCBlock { start: 0x118A0, end: 0x118FF, description: "Warang Citi", tex_name: "warangciti" },
        UCBlock { start: 0x11A00, end: 0x11A4F, description: "Zanabazar Square", tex_name: "zanabazarsquare" },
        UCBlock { start: 0x11A50, end: 0x11AAF, description: "Soyombo", tex_name: "soyombo" },
        UCBlock { start: 0x11AC0, end: 0x11AFF, description: "Pau Cin Hau", tex_name: "paucinhau" },
        UCBlock { start: 0x11C00, end: 0x11C6F, description: "Bhaiksuki", tex_name: "bhaiksuki" },
        UCBlock { start: 0x11C70, end: 0x11CBF, description: "Marchen", tex_name: "marchen" },
        UCBlock { start: 0x11D00, end: 0x11D5F, description: "Masaram Gondi", tex_name: "masaramgondi" },
        UCBlock { start: 0x12000, end: 0x123FF, description: "Cuneiform", tex_name: "cuneiform" },
        UCBlock { start: 0x12400, end: 0x1247F, description: "Cuneiform Numbers and Punctuation", tex_name: "cuneiformnumbersandpunctuation" },
        UCBlock { start: 0x12480, end: 0x1254F, description: "Early Dynastic Cuneiform", tex_name: "earlydynasticcuneiform" },
        UCBlock { start: 0x13000, end: 0x1342F, description: "Egyptian Hieroglyphs", tex_name: "egyptianhieroglyphs" },
        UCBlock { start: 0x14400, end: 0x1467F, description: "Anatolian Hieroglyphs", tex_name: "anatolianhieroglyphs" },
        UCBlock { start: 0x16800, end: 0x16A3F, description: "Bamum Supplement", tex_name: "bamumsupplement" },
        UCBlock { start: 0x16A40, end: 0x16A6F, description: "Mro", tex_name: "mro" },
        UCBlock { start: 0x16AD0, end: 0x16AFF, description: "Bassa Vah", tex_name: "bassavah" },
        UCBlock { start: 0x16B00, end: 0x16B8F, description: "Pahawh Hmong", tex_name: "pahawhhmong" },
        UCBlock { start: 0x16F00, end: 0x16F9F, description: "Miao", tex_name: "miao" },
        UCBlock { start: 0x16FE0, end: 0x16FFF, description: "Ideographic Symbols and Punctuation", tex_name: "ideographicsymbolsandpunctuation" },
        UCBlock { start: 0x17000, end: 0x187FF, description: "Tangut", tex_name: "tangut" },
        UCBlock { start: 0x18800, end: 0x18AFF, description: "Tangut Components", tex_name: "tangutcomponents" },
        UCBlock { start: 0x1B000, end: 0x1B0FF, description: "Kana Supplement", tex_name: "kanasupplement" },
        UCBlock { start: 0x1B100, end: 0x1B12F, description: "Kana Extended-A", tex_name: "kanaextendeda" },
        UCBlock { start: 0x1B170, end: 0x1B2FF, description: "Nushu", tex_name: "nushu" },
        UCBlock { start: 0x1BC00, end: 0x1BC9F, description: "Duployan", tex_name: "duployan" },
        UCBlock { start: 0x1BCA0, end: 0x1BCAF, description: "Shorthand Format Controls", tex_name: "shorthandformatcontrols" },
        UCBlock { start: 0x1D000, end: 0x1D0FF, description: "Byzantine Musical Symbols", tex_name: "byzantinemusicalsymbols" },
        UCBlock { start: 0x1D100, end: 0x1D1FF, description: "Musical Symbols", tex_name: "musicalsymbols" },
        UCBlock { start: 0x1D200, end: 0x1D24F, description: "Ancient Greek Musical Notation", tex_name: "ancientgreekmusicalnotation" },
        UCBlock { start: 0x1D300, end: 0x1D35F, description: "Tai Xuan Jing Symbols", tex_name: "taixuanjingsymbols" },
        UCBlock { start: 0x1D360, end: 0x1D37F, description: "Counting Rod Numerals", tex_name: "countingrodnumerals" },
        UCBlock { start: 0x1D400, end: 0x1D7FF, description: "Mathematical Alphanumeric Symbols", tex_name: "mathematicalalphanumericsymbols" },
        UCBlock { start: 0x1D800, end: 0x1DAAF, description: "Sutton SignWriting", tex_name: "suttonsignwriting" },
        UCBlock { start: 0x1E000, end: 0x1E02F, description: "Glagolitic Supplement", tex_name: "glagoliticsupplement" },
        UCBlock { start: 0x1E800, end: 0x1E8DF, description: "Mende Kikakui", tex_name: "mendekikakui" },
        UCBlock { start: 0x1E900, end: 0x1E95F, description: "Adlam", tex_name: "adlam" },
        UCBlock { start: 0x1EE00, end: 0x1EEFF, description: "Arabic Mathematical Alphabetic Symbols", tex_name: "arabicmathematicalalphabeticsymbols" },
        UCBlock { start: 0x1F000, end: 0x1F02F, description: "Mahjong Tiles", tex_name: "mahjongtiles" },
        UCBlock { start: 0x1F030, end: 0x1F09F, description: "Domino Tiles", tex_name: "dominotiles" },
        UCBlock { start: 0x1F0A0, end: 0x1F0FF, description: "Playing Cards", tex_name: "playingcards" },
        UCBlock { start: 0x1F100, end: 0x1F1FF, description: "Enclosed Alphanumeric Supplement", tex_name: "enclosedalphanumericsupplement" },
        UCBlock { start: 0x1F200, end: 0x1F2FF, description: "Enclosed Ideographic Supplement", tex_name: "enclosedideographicsupplement" },
        UCBlock { start: 0x1F300, end: 0x1F5FF, description: "Miscellaneous Symbols and Pictographs", tex_name: "miscellaneoussymbolsandpictographs" },
        UCBlock { start: 0x1F600, end: 0x1F64F, description: "Emoticons", tex_name: "emoticons" },
        UCBlock { start: 0x1F650, end: 0x1F67F, description: "Ornamental Dingbats", tex_name: "ornamentaldingbats" },
        UCBlock { start: 0x1F680, end: 0x1F6FF, description: "Transport and Map Symbols", tex_name: "transportandmapsymbols" },
        UCBlock { start: 0x1F700, end: 0x1F77F, description: "Alchemical Symbols", tex_name: "alchemicalsymbols" },
        UCBlock { start: 0x1F780, end: 0x1F7FF, description: "Geometric Shapes Extended", tex_name: "geometricshapesextended" },
        UCBlock { start: 0x1F800, end: 0x1F8FF, description: "Supplemental Arrows-C", tex_name: "supplementalarrowsc" },
        UCBlock { start: 0x1F900, end: 0x1F9FF, description: "Supplemental Symbols and Pictographs", tex_name: "supplementalsymbolsandpictographs" },
        UCBlock { start: 0x20000, end: 0x2A6DF, description: "CJK Unified Ideographs Extension B", tex_name: "cjkunifiedideographsextensionb" },
        UCBlock { start: 0x2A700, end: 0x2B73F, description: "CJK Unified Ideographs Extension C", tex_name: "cjkunifiedideographsextensionc" },
        UCBlock { start: 0x2B740, end: 0x2B81F, description: "CJK Unified Ideographs Extension D", tex_name: "cjkunifiedideographsextensiond" },
        UCBlock { start: 0x2B820, end: 0x2CEAF, description: "CJK Unified Ideographs Extension E", tex_name: "cjkunifiedideographsextensione" },
        UCBlock { start: 0x2CEB0, end: 0x2EBEF, description: "CJK Unified Ideographs Extension F", tex_name: "cjkunifiedideographsextensionf" },
        UCBlock { start: 0x2F800, end: 0x2FA1F, description: "CJK Compatibility Ideographs Supplement", tex_name: "cjkcompatibilityideographssupplement" },
        UCBlock { start: 0xE0000, end: 0xE007F, description: "Tags", tex_name: "tags" },
        UCBlock { start: 0xE0100, end: 0xE01EF, description: "Variation Selectors Supplement", tex_name: "variationselectorssupplement" },
        UCBlock { start: 0xF0000, end: 0xFFFFF, description: "Supplementary Private Use Area-A", tex_name: "supplementaryprivateuseareaa" },
        UCBlock { start: 0x100000, end: 0x10FFFF, description: "Supplementary Private Use Area-B", tex_name: "supplementaryprivateuseareab" },
    ];
    return UC_BLOCKS;
}

pub fn get_uc_block(tex_name: &str) -> Option<UCBlock> {
    let uc_blocks = get_uc_blocks();

    for block in uc_blocks {
        if block.tex_name == tex_name {
            return Some(block);
        }
    }

    return None;
}
